### ISSUE TITLE
gemspec missing dependency on json

### ISSUE THREAD

**Issue by betelgeuse** [jpoz/APNS#3]
<pre>
$ cat Gemfile
source :rubygems
gem 'apns'

irb(main):002:0> require 'bundler/setup'
=> true
irb(main):004:0> require 'apns'
LoadError: no such file to load -- json
        from /usr/local/lib/ruby/gems/1.8/gems/apns-0.9.0/lib/apns/core.rb:4:in `require'
        from /usr/local/lib/ruby/gems/1.8/gems/apns-0.9.0/lib/apns/core.rb:4
        from /usr/local/lib/ruby/gems/1.8/gems/apns-0.9.0/lib/apns.rb:1:in `require'
        from /usr/local/lib/ruby/gems/1.8/gems/apns-0.9.0/lib/apns.rb:1
        from (irb):4:in `require'
        from (irb):4
</pre>

As json is used the gemspec should declare a dependency on it.

**Comment by gerrit** [comment]
This is still an issue
